name: local.services.postgres

services:
  services.postgres:
    image: postgres:latest
    restart: always
    container_name: services.postgres
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - ./storage:/var/lib/postgresql/data/

volumes:
  db-data:
    name: services.postgres.volume
    driver: local